# Generated by Django 2.0.3 on 2018-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180416_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
